#!/bin/bash



#ffmpeg -f x11grab -s 1366x768 -i :0.0 out.mkv
#ffmpeg -i /dev/video0 out1.mkv


if [[-f ~/output.mkv]]
then
	n=1
	while [[ -f $HOME/output_$n.mkv]]
	do
        n=$((n+1))
	done
	filename="$HOME/output_$n.mkv"
else
	filename="$HOME/output.mkv"
fi


ffmpeg -y\
-f x11grab\
-s $(xdpyinfo | grep dimensions | awk '{print $2;}')\
-i :0.0\
-i :/dev/video0
-thread_queue_size 1024\
-f alsa -i default\
-c:v libx264 -r 30 -c:a flac $filename
#-c:v ffvhuff -r 30 -c:a flac $filename
#-f pulse -ac 1 -ar 44100 -i default \
